# Generated by Django 4.1.3 on 2022-11-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_addres_customuser_ban_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Электронная почта"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="type",
            field=models.CharField(
                choices=[("AD", "Администратор"), ("DO", "Доктор"), ("CL", "Клиент")],
                default="CL",
                max_length=6,
                verbose_name="Тип пользователя",
            ),
        ),
    ]
