# Generated by Django 4.1.3 on 2022-11-17 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_options_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vizit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=240, null=True)),
                (
                    "documents",
                    models.FileField(
                        blank=True, null=True, upload_to="media/%Y/%m/%d/"
                    ),
                ),
                ("info", models.TextField(blank=True, null=True, verbose_name="")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Визит", "verbose_name_plural": "Визиты",},
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
        migrations.CreateModel(
            name="MedCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "height",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Рост"
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Вес"
                    ),
                ),
                (
                    "blood",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Группа крови",
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Возраст"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={"verbose_name": "Карта", "verbose_name_plural": "Карты",},
        ),
    ]
