# Generated by Django 4.1.3 on 2022-11-18 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_medcard_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="vizit",
            name="date_purpose",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата посещения"
            ),
        ),
        migrations.AddField(
            model_name="vizit",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vizit_doctor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Врач",
            ),
        ),
        migrations.AddField(
            model_name="vizit",
            name="purpose",
            field=models.TextField(blank=True, null=True, verbose_name="Цель визита"),
        ),
        migrations.AddField(
            model_name="vizit",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Посещение завершено"),
        ),
        migrations.AlterField(
            model_name="vizit",
            name="info",
            field=models.TextField(blank=True, null=True, verbose_name="Жалобы"),
        ),
        migrations.AlterField(
            model_name="vizit",
            name="title",
            field=models.CharField(
                blank=True, max_length=240, null=True, verbose_name="Цель визита"
            ),
        ),
        migrations.AlterField(
            model_name="vizit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vizit_client",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Клиент",
            ),
        ),
    ]
