# Generated by Django 4.1.3 on 2022-11-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_vizit_date_purpose_vizit_doctor_vizit_purpose_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logs",
                    models.BooleanField(
                        default=True, verbose_name="Доступ к вкладке логи"
                    ),
                ),
                (
                    "delete",
                    models.BooleanField(
                        default=True, verbose_name="Доступ к удалению документов"
                    ),
                ),
                (
                    "downloads",
                    models.BooleanField(
                        default=True, verbose_name="Доступ к скачиванию документов"
                    ),
                ),
                (
                    "views",
                    models.BooleanField(
                        default=True, verbose_name="Доступ к просмотру документов"
                    ),
                ),
                (
                    "phones",
                    models.BooleanField(
                        default=True, verbose_name="Доступ к просмотру телефонов"
                    ),
                ),
                (
                    "pasports",
                    models.BooleanField(
                        default=True, verbose_name="Доступ к паспортным данным"
                    ),
                ),
                (
                    "documents",
                    models.BooleanField(
                        default="True", verbose_name="Доступ к вкладке документы"
                    ),
                ),
                (
                    "settings",
                    models.BooleanField(
                        default="True",
                        verbose_name="Доступ к вкладке настройка пользователей",
                    ),
                ),
                (
                    "all_info",
                    models.BooleanField(
                        default="True",
                        verbose_name="Доступ к информации о всех пациентах",
                    ),
                ),
                (
                    "my_info",
                    models.BooleanField(
                        default="True",
                        verbose_name="Доступ к информации о своих пациентах",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="all_info",
            field=models.BooleanField(
                default="True", verbose_name="Доступ к информации о всех пациентах"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="delete",
            field=models.BooleanField(
                default=True, verbose_name="Доступ к удалению документов"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="documents",
            field=models.BooleanField(
                default="True", verbose_name="Доступ к вкладке документы"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="downloads",
            field=models.BooleanField(
                default=True, verbose_name="Доступ к скачиванию документов"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="ecp",
            field=models.BooleanField(default=False, verbose_name="Наличие ЭЦП"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="logs",
            field=models.BooleanField(
                default=True, verbose_name="Доступ к вкладке логи"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="my_info",
            field=models.BooleanField(
                default="True", verbose_name="Доступ к информации о своих пациентах"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="pasports",
            field=models.BooleanField(
                default=True, verbose_name="Доступ к паспортным данным"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phones",
            field=models.BooleanField(
                default=True, verbose_name="Доступ к просмотру телефонов"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="settings",
            field=models.BooleanField(
                default="True", verbose_name="Доступ к вкладке настройка пользователей"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="views",
            field=models.BooleanField(
                default=True, verbose_name="Доступ к просмотру документов"
            ),
        ),
    ]
