# Generated by Django 4.1.3 on 2022-11-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_customuser_all_info_alter_customuser_delete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="uniq_id",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Уникальный ID"
            ),
        ),
    ]
