# Generated by Django 4.1.3 on 2022-11-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_customuser_uniq_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="type",
            field=models.CharField(
                choices=[
                    ("AD", "Администратор"),
                    ("DO", "Доктор"),
                    ("CL", "Клиент"),
                    ("DI", "Руководитель"),
                ],
                default="CL",
                max_length=6,
                verbose_name="Тип пользователя",
            ),
        ),
    ]
