# Generated by Django 4.1.4 on 2023-01-17 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='document_deleted',
        ),
        migrations.RemoveField(
            model_name='action',
            name='document_signed',
        ),
        migrations.RemoveField(
            model_name='action',
            name='document_unsigned',
        ),
        migrations.AddField(
            model_name='action',
            name='action',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='action',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
