# Generated by Django 4.1.5 on 2023-01-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_customuser_all_info_remove_customuser_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата Рождения'),
        ),
    ]
