# Generated by Django 4.1.4 on 2023-01-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_customuser_date_of_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ban_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
