# Generated by Django 4.1.4 on 2023-01-30 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_customuser_ban_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ban',
        ),
    ]
