# Generated by Django 4.1.4 on 2023-01-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_customuser_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ban',
            field=models.BooleanField(default=False, verbose_name='Уволен'),
        ),
    ]
