# Generated by Django 4.1.4 on 2023-01-30 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_customuser_ban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ban_date',
        ),
    ]
