# Generated by Django 4.1.4 on 2023-01-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_customuser_ban_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='outside',
            new_name='ban_date',
        ),
    ]
