# Generated by Django 4.1.4 on 2023-02-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_rename_outside_customuser_ban_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='../static/images/default_avatar.png', upload_to='users/%Y/%m/%d/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='uniq_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Уникальный ID'),
        ),
    ]
