# Generated by Django 4.1.4 on 2023-02-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_customuser_photo_alter_customuser_uniq_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('AD', 'Администратор'), ('DO', 'Врач'), ('CL', 'Клиент'), ('DI', 'Руководитель')], default='CL', max_length=6, verbose_name='Тип пользователя'),
        ),
    ]
