# Generated by Django 4.1.4 on 2023-02-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=1111111111, max_length=24, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
