# Generated by Django 4.1.4 on 2023-03-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-pub_date']},
        ),
    ]
