# Generated by Django 4.1.3 on 2022-11-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="type_document",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DOGOVOR", "Договор"),
                    ("IDS", "ИДС"),
                    ("MEDCARD", "Мед карта"),
                    ("ADMCARD", "Адм.карта"),
                    ("SPARVKANAL", "Справка в налоговую"),
                    ("PLANLECH", "План лечения"),
                ],
                max_length=240,
                null=True,
            ),
        ),
    ]
