# Generated by Django 4.1.3 on 2022-11-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_type_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="type_document",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Договор", "Договор"),
                    ("ИДС", "ИДС"),
                    ("Мед.карта", "Мед карта"),
                    ("Адм.карта", "Адм.карта"),
                    ("Справка в налоговую", "Справка в налоговую"),
                    ("План лечения", "План лечения"),
                ],
                max_length=240,
                null=True,
            ),
        ),
    ]
