# Generated by Django 4.1.3 on 2022-11-18 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_alter_document_type_document"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documenttype",
            options={
                "verbose_name": "Тип Документа",
                "verbose_name_plural": "Типы Документов",
            },
        ),
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document",
                to="documents.documenttype",
            ),
        ),
    ]
