# Generated by Django 4.1.3 on 2022-11-27 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0004_alter_documenttype_options_alter_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="founder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="founder",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель документа",
            ),
        ),
    ]
