# Generated by Django 4.1.3 on 2022-11-29 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0006_documenttype_type_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="type_document",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DOGOVOR", "Договор"),
                    ("IDS", "ИДС"),
                    ("MEDCARD", "Мед карта"),
                    ("ADMCARD", "Адм.карта"),
                    ("RENT", "Справка в налоговую"),
                    ("PLAN", "План лечения"),
                    ("DNEVNIK", "Дневник"),
                    ("OTKAZ", "Отказ от мед.вмешательства"),
                ],
                max_length=240,
                null=True,
            ),
        ),
    ]
