# Generated by Django 4.1.3 on 2022-11-29 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0007_document_user_alter_documenttype_type_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documenter",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
