# Generated by Django 4.1.4 on 2023-02-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_document_deleted_document_edit_date_document_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sig',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
